// ============================================================================
//  Grapes — Cantine reali con storie, foto e prezzi verificati sui siti
//  ufficiali (o, dove indicato con price_estimated, prezzi correnti di
//  mercato in mancanza di e-shop ufficiale). Prototipo dimostrativo.
// ============================================================================

export const WINERIES = [
  {
    id: "suentu",
    name: "Cantine Su'entu",
    town: "Sanluri",
    region: "Sardegna",
    localita: "Sanluri",
    lat: 39.5619,
    lng: 8.8996,
    practices: [],
    founded: 2014,
    story_it:
      "Su'entu — \"il vento\" in sardo — nasce dal sogno di Salvatore Pilloni di tornare alle origini vitivinicole della sua famiglia: nel 2009 impianta nuovi vigneti sulle colline di Sanluri e nel 2014 apre la cantina, oggi guidata con i figli Valeria, Roberta e Nicola. La tenuta si estende su 80 ettari, di cui 32 vitati, nel cuore della Marmilla, di cui Su'entu è stata la prima cantina a rivendicare l'IGT. Vitigni simbolo: Bovale, Cannonau e Nasco.",
    story_en:
      "Su'entu — \"the wind\" in Sardinian — was born from Salvatore Pilloni's dream of returning to his family's winemaking roots: he planted new vineyards on the hills of Sanluri in 2009 and opened the winery in 2014, today run with his children Valeria, Roberta and Nicola. The estate covers 80 hectares, 32 under vine, in the heart of the Marmilla, where Su'entu was the first winery to bottle under the Marmilla IGT. Signature grapes: Bovale, Cannonau and Nasco.",
    website: "https://www.cantinesuentu.com",
    image: "https://www.cantinesuentu.com/img/gallery_home_01_800x800.jpg",
    wines: [
      {
        id: "suentu-suanima",
        name: "Su'Anima",
        denom: "Cannonau di Sardegna DOC",
        type: "rosso",
        price: 14.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinesuentu.com/img/suanima_vino-300x300.png",
      },
      {
        id: "suentu-suditerra",
        name: "Su'Diterra",
        denom: "Bovale Marmilla IGT",
        type: "rosso",
        price: 14.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinesuentu.com/img/suditerra_vino-300x300.png",
      },
      {
        id: "suentu-sunico",
        name: "Su'Nico",
        denom: "Bovale Marmilla Rosso IGT",
        type: "rosso",
        price: 25.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinesuentu.com/img/sunico_vino-300x300.png",
      },
      {
        id: "suentu-suaro",
        name: "Su'Aro",
        denom: "Marmilla Bianco IGT",
        type: "bianco",
        price: 13.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinesuentu.com/img/suaro_vino-300x300.png",
      },
    ],
  },
  {
    id: "dolianova",
    name: "Cantine di Dolianova",
    town: "Dolianova",
    region: "Sardegna",
    localita: "Dolianova",
    lat: 39.3768,
    lng: 9.1283,
    practices: [],
    founded: 1949,
    story_it:
      "Fondata nel 1949 da un gruppo di viticoltori del Parteolla che scelsero di unirsi in cooperativa, Cantine di Dolianova è oggi la più grande realtà vitivinicola della Sardegna: oltre 300 soci e circa 1.200 ettari di vigneti in un territorio con tremila anni di cultura del vino. Produce più di 4 milioni di bottiglie l'anno, esportate nei cinque continenti, dai vitigni tipici sardi: Cannonau, Vermentino, Nuragus, Monica e Moscato.",
    story_en:
      "Founded in 1949 by a group of Parteolla winegrowers who joined forces as a cooperative, Cantine di Dolianova is today the largest winery in Sardinia, with over 300 member growers and some 1,200 hectares of vineyards in a land with three thousand years of wine culture. It produces more than 4 million bottles a year, exported to five continents, from Sardinia's native grapes: Cannonau, Vermentino, Nuragus, Monica and Moscato.",
    website: "https://www.cantinedidolianova.it",
    image: "https://www.cantinedidolianova.it/wp-content/uploads/2016/10/LaCantina_LaStoria_Full.jpg",
    wines: [
      {
        id: "dolianova-prendas",
        name: "Prendas",
        denom: "Vermentino di Sardegna DOC",
        type: "bianco",
        price: 10.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinedidolianova.it/wp-content/uploads/2020/08/Prendas_1200x400.jpg",
      },
      {
        id: "dolianova-anzenas",
        name: "Anzenas",
        denom: "Cannonau di Sardegna DOC",
        type: "rosso",
        price: 9.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinedidolianova.it/wp-content/uploads/2020/08/Anzenas_1200x400.jpg",
      },
      {
        id: "dolianova-perlas",
        name: "Perlas",
        denom: "Nuragus di Cagliari DOC",
        type: "bianco",
        price: 9.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinedidolianova.it/wp-content/uploads/2020/08/Perlas_1200x400.jpg",
      },
      {
        id: "dolianova-montesicci",
        name: "Montesicci",
        denom: "Nasco di Cagliari DOC",
        type: "bianco",
        price: 13.0,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinedidolianova.it/wp-content/uploads/2021/12/Montesicci-dolia-2021-1200x400-1.jpg",
      },
    ],
  },
  {
    id: "contini",
    name: "Cantina Contini 1898",
    town: "Cabras (Oristano)",
    region: "Sardegna",
    localita: "Cabras",
    lat: 39.9283,
    lng: 8.5323,
    practices: [],
    founded: 1898,
    story_it:
      "Fondata nel 1898 a Cabras da Salvatore Contini e da sua moglie Anna Maria Dessì, la Contini 1898 è la più antica cantina della Sardegna, guidata ancora oggi dalla stessa famiglia. Nel cuore della penisola del Sinis, tra il mare e gli stagni di Cabras, custodisce il vitigno simbolo del territorio, la Vernaccia di Oristano, affinata sotto flor in botti scolme di rovere e castagno.",
    story_en:
      "Founded in 1898 in Cabras by Salvatore Contini and his wife Anna Maria Dessì, Contini 1898 is Sardinia's oldest winery, still run by the same family today. In the heart of the Sinis peninsula, between the sea and the Cabras lagoons, it safeguards the territory's signature grape, Vernaccia di Oristano, aged under flor in partly-filled oak and chestnut casks.",
    website: "https://www.vinicontini.com",
    image:
      "https://vinicontini.com/wp-content/uploads/2023/05/Cantina-Bottaia-Sardegna-Contini1898-uai-1854x1236.jpg",
    wines: [
      {
        id: "contini-tyrsos",
        name: "Tyrsos",
        denom: "Vermentino di Sardegna DOC",
        type: "bianco",
        price: 10.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://vinicontini.com/wp-content/uploads/2023/05/Tyrsos-Vermentino-Sardegna-DOC.png",
      },
      {
        id: "contini-vernaccia-flor",
        name: "Vernaccia Flor",
        denom: "Vernaccia di Oristano DOC",
        type: "bianco",
        price: 17.4,
        price_estimated: true,
        format: "0.75L",
        image: "https://vinicontini.com/wp-content/uploads/2023/05/Vernaccia-Oristano-DOC.png",
      },
      {
        id: "contini-inu",
        name: "'Inu Riserva",
        denom: "Cannonau di Sardegna DOC Riserva",
        type: "rosso",
        price: 18.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://vinicontini.com/wp-content/uploads/2023/05/Inu-Cannonau-Sardegna-DOC-Riserva.png",
      },
      {
        id: "contini-antico-gregori",
        name: "Antico Gregori",
        denom: "Vernaccia di Oristano DOC Riserva",
        type: "meditazione",
        price: 73.1,
        price_estimated: true,
        format: "0.375L",
        image: "https://vinicontini.com/wp-content/uploads/2023/06/AnticoGregori_Riserva_1991_Contini-1.png",
      },
    ],
  },
  {
    id: "monserrato",
    name: "Cantine Pauli's — Monserrato 1924",
    town: "Monserrato (Cagliari)",
    region: "Sardegna",
    localita: "Monserrato",
    lat: 39.2567,
    lng: 9.144,
    practices: [],
    founded: 1924,
    story_it:
      "Fondata il 6 luglio 1924 da 79 viticoltori, la Cantina Sociale di Monserrato è la più antica cantina sociale della Sardegna, oggi attiva con il marchio Cantine Pauli's. I vigneti dei soci si estendono per circa 300 ettari nel sud dell'isola, coltivati con i vitigni storici sardi: Monica, Nuragus, Vermentino, Cannonau, Nasco e Moscato. Nel 2024 la cooperativa ha celebrato il centenario.",
    story_en:
      "Founded on 6 July 1924 by 79 winegrowers, the Cantina Sociale di Monserrato is Sardinia's oldest cooperative winery, today trading as Cantine Pauli's. Its members' vineyards cover around 300 hectares in the south of the island, planted with the historic Sardinian varieties Monica, Nuragus, Vermentino, Cannonau, Nasco and Moscato. In 2024 the cooperative celebrated its centenary.",
    website: "https://cantinepaulis.it",
    image:
      "https://cantinepaulis.it/wp-content/uploads/cantine-paulis-monserrato-dal-1924-scelte-di-vite.jpg",
    wines: [
      {
        id: "paulis-chea",
        name: "Chea",
        denom: "Monica di Sardegna DOC",
        type: "rosso",
        price: 11.0,
        price_estimated: true,
        format: "0.75L",
        image: "https://cantinepaulis.it/wp-content/uploads/chea-monica-di-sardegna-doc-cantine-paulis-monserrato.png",
      },
      {
        id: "paulis-movida",
        name: "Movida",
        denom: "Nuragus di Cagliari DOC",
        type: "bianco",
        price: 11.0,
        price_estimated: true,
        format: "0.75L",
        image: "https://cantinepaulis.it/wp-content/uploads/movida-nuragus-di-cagliari-doc-cantine-paulis-monserrato.png",
      },
      {
        id: "paulis-evento",
        name: "Evento",
        denom: "Vermentino di Sardegna DOC",
        type: "bianco",
        price: 11.0,
        price_estimated: true,
        format: "0.75L",
        image: "https://cantinepaulis.it/wp-content/uploads/evento-vermentino-di-sardegna-doc-cantine-paulis-monserrato.png",
      },
    ],
  },
  {
    id: "guerrieri-rizzardi",
    name: "Guerrieri Rizzardi",
    town: "Bardolino (Verona)",
    region: "Veneto",
    localita: "Bardolino",
    lat: 45.5464,
    lng: 10.7218,
    practices: [],
    founded: 1678,
    story_it:
      "I Rizzardi coltivano vigne in Valpolicella dal 1649 e imbottigliano i loro vini dal 1678, mentre i conti Guerrieri sviluppavano vino e olio nell'entroterra di Bardolino fin dal Seicento. Nel 1913 il matrimonio tra le due casate diede vita al nome Guerrieri Rizzardi. Oggi la terza generazione guida 100 ettari di vigneti di famiglia tra Bardolino, Valpolicella (tenuta Pojega a Negrar) e Soave, dove la Corvina firma Bardolino, Ripasso e Amarone.",
    story_en:
      "The Rizzardi family has farmed vineyards in Valpolicella since 1649 and bottled its wines since 1678, while the Counts Guerrieri built up wine and olive estates around Bardolino from the 1600s. The 1913 marriage of the two houses created the Guerrieri Rizzardi name. Today the third generation runs 100 hectares of family vineyards across Bardolino, Valpolicella (the Pojega estate in Negrar) and Soave, where Corvina shapes their Bardolino, Ripasso and Amarone.",
    website: "https://www.guerrieri-rizzardi.it",
    image: "https://www.guerrieri-rizzardi.it/wp-content/uploads/2020/04/Storia-Guerrieri-Rizzardi-header.jpg",
    wines: [
      {
        id: "gr-3cru",
        name: "3CRU 2021",
        denom: "Amarone della Valpolicella Classico DOCG",
        type: "rosso",
        price: 36.0,
        format: "0.75L",
        image: "https://www.guerrieri-rizzardi.it/wp-content/uploads/2021/09/Bottiglie-3CRU-Amarone-Della-Valpolicella-DOCG-Classico-Guerrieri-Rizzardi_store-1.jpg",
      },
      {
        id: "gr-pojega",
        name: "Pojega 2024",
        denom: "Valpolicella Ripasso Classico Superiore DOC",
        type: "rosso",
        price: 17.0,
        format: "0.75L",
        image: "https://www.guerrieri-rizzardi.it/wp-content/uploads/2020/11/Bottiglie-pojega-valpolicella-ripasso-classico-superiore-doc_store.jpg",
      },
      {
        id: "gr-cuveexx",
        name: "Cuvée XX 2025",
        denom: "Soave Classico DOC",
        type: "bianco",
        price: 9.0,
        format: "0.75L",
        image: "https://www.guerrieri-rizzardi.it/wp-content/uploads/2020/08/Bottiglie-Soave-Classico-Doc-CuveeXX-vino-bianco-Guerrieri-rizzardi.jpg",
      },
      {
        id: "gr-keya",
        name: "Keya 2025",
        denom: "Chiaretto di Bardolino Classico DOC",
        type: "rosato",
        price: 10.0,
        format: "0.75L",
        image: "https://www.guerrieri-rizzardi.it/wp-content/uploads/2021/05/Bottiglie-Keya-Chiaretto-vino-rosato-Guerrieri-Rizzardi_store.jpg",
      },
    ],
  },
  {
    id: "tasca-dalmerita",
    name: "Tasca d'Almerita",
    town: "Sclafani Bagni (Palermo)",
    region: "Sicilia",
    localita: "Sclafani Bagni",
    lat: 37.8228,
    lng: 13.8451,
    practices: [],
    founded: 1830,
    story_it:
      "Nel 1830 i fratelli Tasca acquistarono la Tenuta Regaleali, un'oasi verde di 550 ettari nella contea di Sclafani, nel cuore della Sicilia. Da quasi due secoli e otto generazioni la famiglia Tasca d'Almerita valorizza i vitigni autoctoni dell'isola — su tutti il Nero d'Avola della storica vigna San Lucio, da cui nasce il Rosso del Conte. A Regaleali si sono aggiunte le tenute Capofaro a Salina, Whitaker a Mozia, Sallier de La Tour a Monreale e Tascante sull'Etna.",
    story_en:
      "In 1830 the Tasca brothers purchased Tenuta Regaleali, a 550-hectare green oasis in the county of Sclafani in the heart of Sicily. For nearly two centuries and eight generations the Tasca d'Almerita family has championed the island's native grapes — above all the Nero d'Avola of the historic San Lucio vineyard, the cradle of Rosso del Conte. To Regaleali they added the Capofaro estate on Salina, Whitaker on Mozia, Sallier de La Tour in Monreale and Tascante on Etna.",
    website: "https://tascadalmerita.it",
    image: "https://cdn.tascadalmerita.it/tasca/Tenuta-regaleali-casa_img_SocialCard.jpg",
    wines: [
      {
        id: "tasca-rosso-conte",
        name: "Rosso del Conte 2019",
        denom: "Contea di Sclafani Rosso DOC",
        type: "rosso",
        price: 55.0,
        format: "0.75L",
        image: "https://cdn.shopify.com/s/files/1/0620/5145/1073/files/RDC_2019_shop.webp",
      },
      {
        id: "tasca-nozze-oro",
        name: "Nozze d'Oro 2024",
        denom: "Sicilia Bianco DOC",
        type: "bianco",
        price: 30.0,
        format: "0.75L",
        image: "https://cdn.shopify.com/s/files/1/0620/5145/1073/files/Tenuta_regaleali_Nozzed_oro_shop_2024.webp",
      },
      {
        id: "tasca-ghiaia-nera",
        name: "Ghiaia Nera 2024",
        denom: "Etna Rosso DOC",
        type: "rosso",
        price: 24.5,
        format: "0.75L",
        image: "https://cdn.shopify.com/s/files/1/0620/5145/1073/files/Tenuta-Tascante-Ghiaia-Nera-2024-shop.webp",
      },
      {
        id: "tasca-lamuri",
        name: "Lamuri 2022",
        denom: "Sicilia Rosso DOC",
        type: "rosso",
        price: 14.5,
        format: "0.75L",
        image: "https://cdn.shopify.com/s/files/1/0620/5145/1073/files/tenuta-regaleali-lamuri-2022-shop_1.webp",
      },
    ],
  },
  {
    id: "ricasoli",
    name: "Ricasoli 1141",
    town: "Gaiole in Chianti (Siena)",
    region: "Toscana",
    localita: "Gaiole in Chianti",
    lat: 43.4669,
    lng: 11.4344,
    practices: [],
    founded: 1141,
    story_it:
      "La famiglia Ricasoli è legata al Castello di Brolio, a Gaiole in Chianti, dal 1141: quasi nove secoli di storia che ne fanno la più antica azienda vinicola d'Italia. Nel 1872 il barone Bettino Ricasoli ideò la formula del Chianti, oggi Chianti Classico, fondata sul Sangiovese. Dal 1993 il barone Francesco Ricasoli guida la tenuta di 1.200 ettari, con circa 240 ettari di vigneto.",
    story_en:
      "The Ricasoli family has been tied to Brolio Castle in Gaiole in Chianti since 1141 — nearly nine centuries of history that make it Italy's oldest winery. In 1872 Baron Bettino Ricasoli devised the formula for Chianti, today's Chianti Classico, built on Sangiovese. Since 1993 Baron Francesco Ricasoli has led the 1,200-hectare estate, with some 240 hectares of vineyards.",
    website: "https://www.ricasoli.com",
    image: "https://www.ricasoli.com/wp-content/uploads/2025/06/Ricasoli_Vigneto.jpg",
    wines: [
      {
        id: "ricasoli-brolio",
        name: "Brolio 2024",
        denom: "Chianti Classico DOCG",
        type: "rosso",
        price: 16.5,
        format: "0.75L",
        image: "https://eshop.ricasoli.com/media/img/product/671/Brolio_2019NV_ombra_full.png",
      },
      {
        id: "ricasoli-brolio-riserva",
        name: "Brolio Riserva 2023",
        denom: "Chianti Classico Riserva DOCG",
        type: "rosso",
        price: 24.9,
        format: "0.75L",
        image: "https://eshop.ricasoli.com/media/img/product/679/9562e-Brolio_Ris_2018NV_ombra_full.png",
      },
      {
        id: "ricasoli-castello",
        name: "Castello di Brolio Gran Selezione 2022",
        denom: "Chianti Classico Gran Selezione DOCG",
        type: "rosso",
        price: 49.0,
        format: "0.75L",
        image: "https://eshop.ricasoli.com/media/img/product/599/Castello_Gaiole_NV_full.png",
      },
      {
        id: "ricasoli-colledila",
        name: "Colledilà Gran Selezione 2022",
        denom: "Chianti Classico Gran Selezione DOCG",
        type: "rosso",
        price: 64.0,
        format: "0.75L",
        image: "https://eshop.ricasoli.com/media/img/product/601/Colledil%C3%A0_Gaiole_NV_full.png",
      },
    ],
  },
  {
    id: "1701-franciacorta",
    name: "1701 Franciacorta",
    town: "Cazzago San Martino (BS)",
    region: "Lombardia",
    localita: "Cazzago San Martino",
    lat: 45.581,
    lng: 10.0244,
    practices: ["biodinamica", "biologica"],
    founded: 2012,
    story_it:
      "Su un brolo di origini medievali a Cazzago San Martino — dove un documento del 1701 attesta per la prima volta la produzione di vino — i fratelli Federico e Silvia Stefini hanno dato vita nel 2012 alla prima cantina biodinamica della Franciacorta, certificata biologica dal 2015 e Demeter dal 2016. Circa 10 ettari di Chardonnay e Pinot Nero per 50.000 bottiglie l'anno, senza chimica di sintesi e con lunghi affinamenti sui lieviti.",
    story_en:
      "On a medieval walled vineyard in Cazzago San Martino — where a 1701 document first attests to wine production — siblings Federico and Silvia Stefini founded Franciacorta's first biodynamic winery in 2012, certified organic in 2015 and Demeter in 2016. Around 10 hectares of Chardonnay and Pinot Nero yield 50,000 bottles a year, farmed without synthetic chemistry and aged long on the lees.",
    website: "https://1701franciacorta.com",
    image: "https://1701franciacorta.com/cdn/shop/files/1701-azienda-territorio_2048x2048.jpg?v=1648539020",
    wines: [
      {
        id: "1701-franciacorta-1701-brut-nature",
        name: "1701 Brut Nature",
        denom: "Franciacorta DOCG Brut Nature",
        type: "bollicine",
        price: 26.0,
        format: "0.75L",
        image: "https://cdn.shopify.com/s/files/1/0264/6687/7530/products/1701-franciacorta-biodnamico-brut-nature-no-bg2.png?v=1761932298",
      },
      {
        id: "1701-franciacorta-1701-saten-raccolta-2021",
        name: "1701 Satèn Raccolta 2021",
        denom: "Franciacorta DOCG Satèn",
        type: "bollicine",
        price: 33.0,
        format: "0.75L",
        image: "https://cdn.shopify.com/s/files/1/0264/6687/7530/files/SatenRaccolta2021.png?v=1756983087",
      },
      {
        id: "1701-franciacorta-1701-rose-nature-raccolta-2021",
        name: "1701 Rosé Nature Raccolta 2021",
        denom: "Franciacorta DOCG Rosé Dosaggio Zero",
        type: "bollicine",
        price: 40.0,
        format: "0.75L",
        image: "https://cdn.shopify.com/s/files/1/0264/6687/7530/files/ROSE-2019.jpg?v=1697097420",
      },
      {
        id: "1701-franciacorta-1701-dosaggio-zero-riserva-2019",
        name: "1701 Dosaggio Zero Riserva 2019",
        denom: "Franciacorta DOCG Riserva Dosaggio Zero",
        type: "bollicine",
        price: 56.0,
        format: "0.75L",
        image: "https://cdn.shopify.com/s/files/1/0264/6687/7530/files/DOSAGGIO-ZERO-2016.jpg?v=1697097261",
      },
    ],
  },
  {
    id: "barone-pizzini",
    name: "Barone Pizzini",
    town: "Provaglio d'Iseo (BS)",
    region: "Lombardia",
    localita: "Provaglio d'Iseo",
    lat: 45.6363,
    lng: 10.043,
    practices: ["biologica"],
    founded: 1870,
    story_it:
      "Fondata nel 1870 dal barone Giulio Pizzini Piomarta a Provaglio d'Iseo, è tra le case storiche della Franciacorta: aderì alla DOC nel 1967 e produsse il suo primo Metodo Classico nel 1971. È la pioniera del biologico in Franciacorta — conversione avviata nel 1998, vigneti certificati nel 2001 e nel 2005 il primo Franciacorta biologico certificato mai messo in commercio. Oggi coltiva circa 60 ettari in 30 parcelle, con una cantina in bioedilizia inaugurata nel 2006.",
    story_en:
      "Founded in 1870 by Baron Giulio Pizzini Piomarta in Provaglio d'Iseo, it is one of Franciacorta's historic houses: a DOC founding member in 1967, it made its first Metodo Classico in 1971. It is Franciacorta's organic pioneer — conversion began in 1998, vineyards were certified in 2001, and in 2005 it released the first certified-organic Franciacorta ever sold. Today it farms some 60 hectares across 30 parcels, with a green-building winery opened in 2006.",
    website: "https://baronepizzini.it",
    image: "https://baronepizzini.it/wp-content/uploads/2025/10/cantina-e1760949673490-768x453.jpg",
    wines: [
      {
        id: "barone-pizzini-animante",
        name: "Animante",
        denom: "Franciacorta DOCG Dosaggio Zero",
        type: "bollicine",
        price: 24.0,
        price_estimated: true,
        format: "0.75L",
        image: "https://baronepizzini.it/wp-content/uploads/2022/07/BP-Animante_small.png",
      },
      {
        id: "barone-pizzini-saten-2021",
        name: "Satèn 2021",
        denom: "Franciacorta DOCG Satèn",
        type: "bollicine",
        price: 33.5,
        price_estimated: true,
        format: "0.75L",
        image: "https://baronepizzini.it/wp-content/uploads/2022/07/BP-saten-small.png",
      },
      {
        id: "barone-pizzini-naturae-2021",
        name: "Naturae 2021",
        denom: "Franciacorta DOCG Brut Nature",
        type: "bollicine",
        price: 33.8,
        price_estimated: true,
        format: "0.75L",
        image: "https://baronepizzini.it/wp-content/uploads/2022/07/BP-Naturae-small.png",
      },
      {
        id: "barone-pizzini-rose-2022",
        name: "Rosé 2022",
        denom: "Franciacorta DOCG Rosé Extra Brut",
        type: "bollicine",
        price: 33.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://baronepizzini.it/wp-content/uploads/2022/07/BP-Rose-small-1.png",
      },
    ],
  },
  {
    id: "arpepe",
    name: "ArPePe — Arturo Pelizzatti Perego",
    town: "Sondrio, Valtellina",
    region: "Lombardia",
    localita: "Sondrio",
    lat: 46.1699,
    lng: 9.8788,
    practices: ["eroica"],
    founded: 1984,
    story_it:
      "La famiglia Pelizzatti Perego produce vino in Valtellina dal 1860; nel 1984 Arturo Pelizzatti Perego, il 'sarto della Sassella', rifonda l'azienda per riportare il Nebbiolo delle Alpi ai vertici della qualità. Oggi la quinta generazione — Emanuele, Isabella e Guido — coltiva i terrazzamenti a secco dei crus Sassella, Grumello e Inferno sopra Sondrio, con lunghi affinamenti in botti di rovere e castagno.",
    story_en:
      "The Pelizzatti Perego family has made wine in Valtellina since 1860; in 1984 Arturo Pelizzatti Perego, the 'Tailor of Sassella', refounded the estate to bring Nebbiolo delle Alpi back to the top of fine wine. Today the fifth generation — Emanuele, Isabella and Guido — farms the dry-stone terraces of the Sassella, Grumello and Inferno crus above Sondrio, with long ageing in oak and chestnut casks.",
    website: "https://www.arpepe.com",
    image: "https://www.arpepe.com/content/img/territorio-small.jpg",
    wines: [
      {
        id: "arpepe-rosso-di-valtellina",
        name: "Rosso di Valtellina",
        denom: "Rosso di Valtellina DOC",
        type: "rosso",
        price: 25.5,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.arpepe.com/public/gallery-vini/950x1440/ARPEPE_Rosso%20di%20Valtellina.jpg",
      },
      {
        id: "arpepe-sassella-stella-retica",
        name: "Sassella Stella Retica",
        denom: "Valtellina Superiore Sassella DOCG",
        type: "rosso",
        price: 42.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.arpepe.com/public/gallery-vini/950x1440/ARPEPE_Sassella_Stella%20Retica.jpg",
      },
      {
        id: "arpepe-grumello-rocca-de-piro",
        name: "Grumello Rocca De Piro",
        denom: "Valtellina Superiore Grumello DOCG",
        type: "rosso",
        price: 42.0,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.arpepe.com/public/gallery-vini/950x1440/ARPEPE_Grumello_Rocca%20De%20Piro.jpg",
      },
      {
        id: "arpepe-sassella-rocce-rosse-riserva",
        name: "Sassella Rocce Rosse Riserva",
        denom: "Valtellina Superiore Sassella Riserva DOCG",
        type: "rosso",
        price: 85.0,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.arpepe.com/public/gallery-vini/950x1440/ARPEPE_Sassella_Rocce%20Rosse.jpg",
      },
    ],
  },
  {
    id: "possa",
    name: "Possa di Heydi Bonanini",
    town: "Riomaggiore, Cinque Terre",
    region: "Liguria",
    localita: "Riomaggiore",
    lat: 44.0997,
    lng: 9.7376,
    practices: ["eroica", "naturale", "biologica"],
    founded: 2004,
    story_it:
      "Nel 2004 Samuele Heydi Bonanini ha recuperato i vigneti terrazzati a picco sul mare di Riomaggiore, nelle Cinque Terre, ricostruendo muretti a secco e vigne abbandonate di Bosco, Albarola e Rossese bianco. Viticoltura eroica pura: cesti in spalla, monorotaie a cremagliera e scalinate tra gli ulivi, per vini naturali e per il leggendario passito Sciacchetrà.",
    story_en:
      "In 2004 Samuele Heydi Bonanini reclaimed Riomaggiore's terraced vineyards hanging over the sea in the Cinque Terre, rebuilding dry-stone walls and abandoned plots of Bosco, Albarola and white Rossese. Pure heroic viticulture: baskets on shoulders, rack monorails and stairways among the olive trees, producing natural wines and the legendary Sciacchetrà passito.",
    website: "https://possa.it",
    image: "https://possa.it/wp-content/uploads/2025/12/possa_vigneto_mare_crop.jpg",
    wines: [
      {
        id: "possa-u-giancu",
        name: "U Giancu",
        denom: "Vino Bianco (100% Albarola)",
        type: "bianco",
        price: 22.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://possa.it/wp-content/uploads/2026/01/er_giancu_header_new.jpg",
      },
      {
        id: "possa-cinque-terre",
        name: "Cinque Terre",
        denom: "Cinque Terre DOC",
        type: "bianco",
        price: 27.5,
        price_estimated: true,
        format: "0.75L",
        image: "https://possa.it/wp-content/uploads/2026/01/cinque_terre_header_prov.jpg",
      },
      {
        id: "possa-u-neigru",
        name: "U Neigru",
        denom: "Vino Rosso",
        type: "rosso",
        price: 21.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://possa.it/wp-content/uploads/2026/01/u_neigru_header_new.jpg",
      },
      {
        id: "possa-cinque-terre-sciacchetra-anfora",
        name: "Cinque Terre Sciacchetrà Anfora",
        denom: "Cinque Terre Sciacchetrà DOC",
        type: "meditazione",
        price: 68.9,
        price_estimated: true,
        format: "0.375L",
        image: "https://possa.it/wp-content/uploads/2026/01/sciacchetra_anfora_header.jpg",
      },
    ],
  },
  {
    id: "cave-mont-blanc",
    name: "Cave Mont Blanc de Morgex et La Salle",
    town: "Morgex (Aosta)",
    region: "Valle d'Aosta",
    localita: "Morgex",
    lat: 45.7549,
    lng: 7.0405,
    practices: ["eroica"],
    founded: 1983,
    story_it:
      "Cooperativa nata nel 1983 a Morgex, ai piedi del Monte Bianco, riunisce circa 80 piccoli viticoltori che coltivano il Prié Blanc a piede franco tra i 900 e i 1.200 metri: i vigneti più alti d'Europa. Dalle pergole basse su terrazzamenti alpini nascono circa 140.000 bottiglie l'anno, compresi spumanti metodo classico affinati in quota alla Skyway Monte Bianco (2.173 m).",
    story_en:
      "A cooperative founded in 1983 in Morgex, at the foot of Mont Blanc, uniting some 80 small growers who farm ungrafted Prié Blanc between 900 and 1,200 metres: Europe's highest vineyards. From low pergolas on alpine terraces come around 140,000 bottles a year, including classic-method sparklers aged at altitude at Skyway Monte Bianco (2,173 m).",
    website: "https://www.cavemontblanc.com",
    image: "https://www.cavemontblanc.com/uploads/page/25/vigneto-la-piagne.jpg",
    wines: [
      {
        id: "cave-mont-blanc-blanc-de-morgex-et-de-la-salle",
        name: "Blanc de Morgex et de La Salle",
        denom: "Valle d'Aosta DOC Blanc de Morgex et de La Salle",
        type: "bianco",
        price: 15.6,
        format: "0.75L",
        image: "https://www.cavemontblanc.com/uploads/product/1/resized/cave.jpg",
      },
      {
        id: "cave-mont-blanc-la-piagne",
        name: "La Piagne",
        denom: "Valle d'Aosta DOC Blanc de Morgex et de La Salle",
        type: "bianco",
        price: 26.9,
        format: "0.75L",
        image: "https://www.cavemontblanc.com/uploads/product/3/resized/piagne.jpg",
      },
      {
        id: "cave-mont-blanc-blanc-du-blanc-brut-metodo-classico",
        name: "Blanc du Blanc Brut Metodo Classico",
        denom: "Valle d'Aosta DOC Blanc de Morgex et de La Salle",
        type: "bollicine",
        price: 22.9,
        format: "0.75L",
        image: "https://www.cavemontblanc.com/uploads/product/7/resized/blanc-du-blanc-brut-new.jpg",
      },
      {
        id: "cave-mont-blanc-glacier-metodo-classico",
        name: "Glacier Metodo Classico",
        denom: "Valle d'Aosta DOC Blanc de Morgex et de La Salle",
        type: "bollicine",
        price: 24.89,
        format: "0.75L",
        image: "https://www.cavemontblanc.com/uploads/product/5/resized/glacier-1.jpg",
      },
    ],
  },
  {
    id: "tenute-dettori",
    name: "Tenute Dettori",
    town: "Sennori (Sassari)",
    region: "Sardegna",
    localita: "Sennori",
    lat: 40.7893,
    lng: 8.5925,
    practices: ["naturale", "biodinamica"],
    founded: 2000,
    story_it:
      "Pastori e agricoltori della Romangia fin dall'Ottocento, i Dettori coltivano a Badde Nigolosu 26 ettari di alberelli non irrigati, con ceppi di Cannonau che risalgono al 1883. Alessandro Dettori, tornato in azienda alla fine degli anni '90, imbottiglia dal 2000 vini a fermentazione spontanea, senza filtrazioni né solfiti aggiunti, e dal 2003 segue l'agricoltura biodinamica. Il Retagliadu Nieddu, antico clone locale di Cannonau, è la sua uva simbolo.",
    story_en:
      "Shepherds and farmers of the Romangia since the 1800s, the Dettori family tends 26 hectares of dry-farmed bush vines at Badde Nigolosu, with Cannonau vines dating back to 1883. Alessandro Dettori, back at the estate in the late 1990s, has bottled spontaneously fermented, unfiltered wines with no added sulfites since 2000, and has farmed biodynamically since 2003. Retagliadu Nieddu, an ancient local Cannonau clone, is his signature grape.",
    website: "https://www.tenutedettori.it",
    image: "https://www.tenutedettori.it/assets/images/BADDE-PANORAMA-1140.webp",
    wines: [
      {
        id: "tenute-dettori-renosu-bianco",
        name: "Renosu Bianco",
        denom: "Vino Bianco da Tavola",
        type: "bianco",
        price: 14.2,
        price_estimated: true,
        format: "0.75L",
      },
      {
        id: "tenute-dettori-dettori-bianco",
        name: "Dettori Bianco",
        denom: "Romangia Bianco IGT",
        type: "bianco",
        price: 35.4,
        price_estimated: true,
        format: "0.75L",
      },
      {
        id: "tenute-dettori-tuderi",
        name: "Tuderi",
        denom: "Romangia Rosso IGT",
        type: "rosso",
        price: 29.5,
        price_estimated: true,
        format: "0.75L",
      },
      {
        id: "tenute-dettori-tenores",
        name: "Tenores",
        denom: "Romangia Rosso IGT",
        type: "rosso",
        price: 45.5,
        price_estimated: true,
        format: "0.75L",
      },
    ],
  },
  {
    id: "giuseppe-sedilesu",
    name: "Giuseppe Sedilesu",
    town: "Mamoiada (Nuoro)",
    region: "Sardegna",
    localita: "Mamoiada",
    lat: 40.2136,
    lng: 9.2834,
    practices: ["biologica", "eroica"],
    founded: 2000,
    story_it:
      "Tutto comincia negli anni '70, quando Giuseppe Sedilesu e la moglie Grazia acquistano una piccola vigna a Mamoiada, nel cuore della Barbagia; nel 2000 i figli imbottigliano per la prima volta il loro Cannonau, battezzandolo Mamuthone in onore della maschera tradizionale del paese. I vigneti ad alberello, su suoli granitici tra i 500 e gli 800 metri, sono coltivati in biologico e custodiscono anche la Granazza, raro clone bianco che secondo l'Università di Sassari esiste solo a Mamoiada.",
    story_en:
      "It all began in the 1970s, when Giuseppe Sedilesu and his wife Grazia bought a small vineyard in Mamoiada, in the heart of the Barbagia; in 2000 their children bottled their Cannonau for the first time, naming it Mamuthone after the village's traditional carnival mask. The head-trained bush vineyards, on granitic soils between 500 and 800 metres, are organically farmed and also preserve Granazza, a rare white clone that University of Sassari studies suggest exists only in Mamoiada.",
    website: "https://www.giuseppesedilesu.it",
    image: "https://www.giuseppesedilesu.it/wp-content/uploads/2022/02/Sedilesu-Web-TeastataVino.jpg",
    wines: [
      {
        id: "giuseppe-sedilesu-mamuthone",
        name: "Mamuthone",
        denom: "Cannonau di Sardegna DOC",
        type: "rosso",
        price: 18.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.giuseppesedilesu.it/wp-content/uploads/2022/03/Mamuthone-uai-258x676.png",
      },
      {
        id: "giuseppe-sedilesu-sartiu",
        name: "Sartiu",
        denom: "Cannonau di Sardegna DOC",
        type: "rosso",
        price: 12.4,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.giuseppesedilesu.it/wp-content/uploads/2022/03/Sartiu-e1727364686624-uai-258x676.png",
      },
      {
        id: "giuseppe-sedilesu-ballu-tundu",
        name: "Ballu Tundu",
        denom: "Cannonau di Sardegna Riserva DOC",
        type: "rosso",
        price: 28.0,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.giuseppesedilesu.it/wp-content/uploads/2022/03/Ballo-tundu-uai-258x676.png",
      },
      {
        id: "giuseppe-sedilesu-perda-pinta",
        name: "Perda Pintà",
        denom: "Barbagia Bianco IGT",
        type: "bianco",
        price: 29.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.giuseppesedilesu.it/wp-content/uploads/2022/03/Perda-Pinta-uai-258x676.png",
      },
    ],
  },
  {
    id: "cantina-berritta",
    name: "Cantina Berritta",
    town: "Dorgali (Nuoro)",
    region: "Sardegna",
    localita: "Dorgali",
    lat: 40.2915,
    lng: 9.5901,
    practices: ["biologica"],
    founded: 2007,
    story_it:
      "Nella valle di Oddoene, a Dorgali, la famiglia Berritta coltiva la vigna da generazioni: nel 2007 il vignaiolo Antonio Berritta fonda la cantina per vinificare in proprio circa 10 ettari su suoli di granito in disfacimento misto a calcare. Certificata biologica dall'annata 2019, produce circa 30.000 bottiglie dominate dal Cannonau, e ha riportato in vita il Panzale, antico vitigno bianco dorgalese quasi estinto.",
    story_en:
      "In the Oddoene valley of Dorgali, the Berritta family has farmed vines for generations: in 2007 grower Antonio Berritta founded the winery to vinify roughly 10 hectares on decomposed granite mixed with limestone. Certified organic from the 2019 vintage, it produces about 30,000 bottles dominated by Cannonau, and has revived Panzale, an ancient nearly extinct white grape of Dorgali.",
    website: "https://www.cantinaberritta.it",
    image: "https://www.cantinaberritta.it/wp-content/themes/cantinaberritta2018-child/images/vigneti_berritta_2000x1333.jpg",
    wines: [
      {
        id: "cantina-berritta-nostranu",
        name: "Nostranu",
        denom: "Cannonau di Sardegna DOC",
        type: "rosso",
        price: 18.0,
        format: "0.75L",
        image: "https://www.cantinaberritta.it/wp-content/uploads/img_nostranu_2020_460x690.jpg",
      },
      {
        id: "cantina-berritta-thurcalesu",
        name: "Thurcalesu",
        denom: "Cannonau di Sardegna DOC",
        type: "rosso",
        price: 23.0,
        format: "0.75L",
        image: "https://www.cantinaberritta.it/wp-content/uploads/img_thurcalesu_2020_460x690.jpg",
      },
      {
        id: "cantina-berritta-monte-tundu",
        name: "Monte Tundu",
        denom: "Cannonau di Sardegna DOC Classico",
        type: "rosso",
        price: 30.0,
        format: "0.75L",
        image: "https://www.cantinaberritta.it/wp-content/uploads/img_montetundu_2020_460x690.jpg",
      },
      {
        id: "cantina-berritta-panzale",
        name: "Panzale",
        denom: "Isola dei Nuraghi IGT Bianco",
        type: "bianco",
        price: 25.0,
        format: "0.75L",
        image: "https://www.cantinaberritta.it/wp-content/uploads/img_panzale_2020_460x690.jpg",
      },
    ],
  },
  {
    id: "fattoria-la-maliosa",
    name: "Fattoria La Maliosa",
    town: "Saturnia, Manciano (Grosseto)",
    region: "Toscana",
    localita: "Manciano",
    lat: 42.6027,
    lng: 11.5083,
    practices: ["naturale", "biodinamica", "biologica"],
    founded: 2005,
    story_it:
      "Fondata nel 2005 da Antonella Manuli, La Maliosa si estende su 170 ettari di colline maremmane tra Saturnia, Montemerano e Pitigliano. Certificata biologica dal 2010 e biodinamica Demeter, produce vini naturali senza additivi né solfiti aggiunti secondo il Metodo Corino, messo a punto con l'agronomo e ricercatore Lorenzo Corino. In vigna vitigni autoctoni come Procanico, Ciliegiolo e Sangiovese, accanto a olivi e miele biologico.",
    story_en:
      "Founded in 2005 by Antonella Manuli, La Maliosa spans 170 hectares of Maremma hills between Saturnia, Montemerano and Pitigliano. Certified organic since 2010 and Demeter biodynamic, it makes natural wines with no additives or added sulphites following the Metodo Corino, developed with agronomist and researcher Lorenzo Corino. The vineyards grow native varieties such as Procanico, Ciliegiolo and Sangiovese, alongside olive groves and organic honey.",
    website: "https://fattorialamaliosa.it",
    image: "https://fattorialamaliosa.it/wp-content/uploads/2024/01/visual2-1568x882.jpg",
    wines: [
      {
        id: "fattoria-la-maliosa-saturnalia-bianco",
        name: "Saturnalia Bianco",
        denom: "IGT Toscana Bianco",
        type: "bianco",
        price: 25.0,
        format: "0.75L",
        image: "https://shop.fattorialamaliosa.it/wp-content/uploads/2025/09/Bottiglia-Saturnalia-bianco.png",
      },
      {
        id: "fattoria-la-maliosa-saturnalia-rosso",
        name: "Saturnalia Rosso",
        denom: "IGT Toscana Rosso",
        type: "rosso",
        price: 21.9,
        format: "0.75L",
        image: "https://shop.fattorialamaliosa.it/wp-content/uploads/2025/09/Saturnalia-Rosso-2022-1.png",
      },
      {
        id: "fattoria-la-maliosa-la-maliosa-rosso",
        name: "La Maliosa Rosso",
        denom: "IGT Toscana Rosso",
        type: "rosso",
        price: 27.0,
        format: "0.75L",
        image: "https://shop.fattorialamaliosa.it/wp-content/uploads/2025/09/La-Maliosa-Rosso.png",
      },
      {
        id: "fattoria-la-maliosa-tarconte",
        name: "Tarconte",
        denom: "IGT Toscana Rosso",
        type: "rosso",
        price: 34.0,
        format: "0.75L",
        image: "https://shop.fattorialamaliosa.it/wp-content/uploads/2025/09/Tarconte-2020.png",
      },
    ],
  },
  {
    id: "stella-di-campalto",
    name: "Stella di Campalto",
    town: "Montalcino (Siena)",
    region: "Toscana",
    localita: "Montalcino",
    lat: 43.009,
    lng: 11.5232,
    practices: ["biodinamica", "biologica"],
    founded: 1992,
    story_it:
      "Nel 1992 Stella di Campalto ha recuperato il Podere San Giuseppe (1910), abbandonato dagli anni Quaranta, sul versante sud-est di Montalcino presso Castelnuovo dell'Abate. Circa 7 ettari di solo Sangiovese in nove parcelle vinificate separatamente, su suoli di galestro, argilla e calcare tra 350 e 450 metri. Certificata biologica dal 2002 e biodinamica dal 2005, produce Brunello e Rosso di Montalcino di culto, artigianali e senza forzature in cantina.",
    story_en:
      "In 1992 Stella di Campalto began restoring Podere San Giuseppe (est. 1910), abandoned since the 1940s, on the south-eastern slope of Montalcino near Castelnuovo dell'Abate. Around 7 hectares of pure Sangiovese across nine parcels vinified separately, on galestro, clay and limestone soils at 350-450 metres. Certified organic since 2002 and biodynamic since 2005, she crafts cult, artisanal Brunello and Rosso di Montalcino with minimal cellar intervention.",
    website: "https://www.stelladicampalto.it",
    image: "https://www.stelladicampalto.it/wp-content/uploads/2019/05/sangiovanni-hero-1024x576.jpg",
    wines: [
      {
        id: "stella-di-campalto-choltempo-fiorello",
        name: "Choltempo Fiorello",
        denom: "IGT Toscana Rosso",
        type: "rosso",
        price: 67.9,
        price_estimated: true,
        format: "0.75L",
      },
      {
        id: "stella-di-campalto-brunello-di-montalcino-cielo-2018",
        name: "Brunello di Montalcino Cielo 2018",
        denom: "Brunello di Montalcino DOCG",
        type: "rosso",
        price: 427.0,
        price_estimated: true,
        format: "0.75L",
      },
      {
        id: "stella-di-campalto-brunello-di-montalcino-aria-2018",
        name: "Brunello di Montalcino Aria 2018",
        denom: "Brunello di Montalcino DOCG",
        type: "rosso",
        price: 427.0,
        price_estimated: true,
        format: "0.75L",
      },
    ],
  },
];
