// ============================================================================
//  Grapes — Cantine reali con storie, foto e prezzi verificati sui siti
//  ufficiali (o, dove indicato con price_estimated, prezzi correnti di
//  mercato in mancanza di e-shop ufficiale). Prototipo dimostrativo.
// ============================================================================

export const WINERIES = [
  {
    id: "suentu",
    name: "Cantine Su'entu",
    town: "Sanluri",
    region: "Sardegna",
    founded: 2014,
    story_it:
      "Su'entu — \"il vento\" in sardo — nasce dal sogno di Salvatore Pilloni di tornare alle origini vitivinicole della sua famiglia: nel 2009 impianta nuovi vigneti sulle colline di Sanluri e nel 2014 apre la cantina, oggi guidata con i figli Valeria, Roberta e Nicola. La tenuta si estende su 80 ettari, di cui 32 vitati, nel cuore della Marmilla, di cui Su'entu è stata la prima cantina a rivendicare l'IGT. Vitigni simbolo: Bovale, Cannonau e Nasco.",
    story_en:
      "Su'entu — \"the wind\" in Sardinian — was born from Salvatore Pilloni's dream of returning to his family's winemaking roots: he planted new vineyards on the hills of Sanluri in 2009 and opened the winery in 2014, today run with his children Valeria, Roberta and Nicola. The estate covers 80 hectares, 32 under vine, in the heart of the Marmilla, where Su'entu was the first winery to bottle under the Marmilla IGT. Signature grapes: Bovale, Cannonau and Nasco.",
    website: "https://www.cantinesuentu.com",
    image: "https://www.cantinesuentu.com/img/gallery_home_01_800x800.jpg",
    wines: [
      {
        id: "suentu-suanima",
        name: "Su'Anima",
        denom: "Cannonau di Sardegna DOC",
        type: "rosso",
        price: 14.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinesuentu.com/img/suanima_vino-300x300.png",
      },
      {
        id: "suentu-suditerra",
        name: "Su'Diterra",
        denom: "Bovale Marmilla IGT",
        type: "rosso",
        price: 14.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinesuentu.com/img/suditerra_vino-300x300.png",
      },
      {
        id: "suentu-sunico",
        name: "Su'Nico",
        denom: "Bovale Marmilla Rosso IGT",
        type: "rosso",
        price: 25.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinesuentu.com/img/sunico_vino-300x300.png",
      },
      {
        id: "suentu-suaro",
        name: "Su'Aro",
        denom: "Marmilla Bianco IGT",
        type: "bianco",
        price: 13.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinesuentu.com/img/suaro_vino-300x300.png",
      },
    ],
  },
  {
    id: "dolianova",
    name: "Cantine di Dolianova",
    town: "Dolianova",
    region: "Sardegna",
    founded: 1949,
    story_it:
      "Fondata nel 1949 da un gruppo di viticoltori del Parteolla che scelsero di unirsi in cooperativa, Cantine di Dolianova è oggi la più grande realtà vitivinicola della Sardegna: oltre 300 soci e circa 1.200 ettari di vigneti in un territorio con tremila anni di cultura del vino. Produce più di 4 milioni di bottiglie l'anno, esportate nei cinque continenti, dai vitigni tipici sardi: Cannonau, Vermentino, Nuragus, Monica e Moscato.",
    story_en:
      "Founded in 1949 by a group of Parteolla winegrowers who joined forces as a cooperative, Cantine di Dolianova is today the largest winery in Sardinia, with over 300 member growers and some 1,200 hectares of vineyards in a land with three thousand years of wine culture. It produces more than 4 million bottles a year, exported to five continents, from Sardinia's native grapes: Cannonau, Vermentino, Nuragus, Monica and Moscato.",
    website: "https://www.cantinedidolianova.it",
    image: "https://www.cantinedidolianova.it/wp-content/uploads/2016/10/LaCantina_LaStoria_Full.jpg",
    wines: [
      {
        id: "dolianova-prendas",
        name: "Prendas",
        denom: "Vermentino di Sardegna DOC",
        type: "bianco",
        price: 10.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinedidolianova.it/wp-content/uploads/2020/08/Prendas_1200x400.jpg",
      },
      {
        id: "dolianova-anzenas",
        name: "Anzenas",
        denom: "Cannonau di Sardegna DOC",
        type: "rosso",
        price: 9.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinedidolianova.it/wp-content/uploads/2020/08/Anzenas_1200x400.jpg",
      },
      {
        id: "dolianova-perlas",
        name: "Perlas",
        denom: "Nuragus di Cagliari DOC",
        type: "bianco",
        price: 9.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinedidolianova.it/wp-content/uploads/2020/08/Perlas_1200x400.jpg",
      },
      {
        id: "dolianova-montesicci",
        name: "Montesicci",
        denom: "Nasco di Cagliari DOC",
        type: "bianco",
        price: 13.0,
        price_estimated: true,
        format: "0.75L",
        image: "https://www.cantinedidolianova.it/wp-content/uploads/2021/12/Montesicci-dolia-2021-1200x400-1.jpg",
      },
    ],
  },
  {
    id: "contini",
    name: "Cantina Contini 1898",
    town: "Cabras (Oristano)",
    region: "Sardegna",
    founded: 1898,
    story_it:
      "Fondata nel 1898 a Cabras da Salvatore Contini e da sua moglie Anna Maria Dessì, la Contini 1898 è la più antica cantina della Sardegna, guidata ancora oggi dalla stessa famiglia. Nel cuore della penisola del Sinis, tra il mare e gli stagni di Cabras, custodisce il vitigno simbolo del territorio, la Vernaccia di Oristano, affinata sotto flor in botti scolme di rovere e castagno.",
    story_en:
      "Founded in 1898 in Cabras by Salvatore Contini and his wife Anna Maria Dessì, Contini 1898 is Sardinia's oldest winery, still run by the same family today. In the heart of the Sinis peninsula, between the sea and the Cabras lagoons, it safeguards the territory's signature grape, Vernaccia di Oristano, aged under flor in partly-filled oak and chestnut casks.",
    website: "https://www.vinicontini.com",
    image:
      "https://vinicontini.com/wp-content/uploads/2023/05/Cantina-Bottaia-Sardegna-Contini1898-uai-1854x1236.jpg",
    wines: [
      {
        id: "contini-tyrsos",
        name: "Tyrsos",
        denom: "Vermentino di Sardegna DOC",
        type: "bianco",
        price: 10.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://vinicontini.com/wp-content/uploads/2023/05/Tyrsos-Vermentino-Sardegna-DOC.png",
      },
      {
        id: "contini-vernaccia-flor",
        name: "Vernaccia Flor",
        denom: "Vernaccia di Oristano DOC",
        type: "bianco",
        price: 17.4,
        price_estimated: true,
        format: "0.75L",
        image: "https://vinicontini.com/wp-content/uploads/2023/05/Vernaccia-Oristano-DOC.png",
      },
      {
        id: "contini-inu",
        name: "'Inu Riserva",
        denom: "Cannonau di Sardegna DOC Riserva",
        type: "rosso",
        price: 18.9,
        price_estimated: true,
        format: "0.75L",
        image: "https://vinicontini.com/wp-content/uploads/2023/05/Inu-Cannonau-Sardegna-DOC-Riserva.png",
      },
      {
        id: "contini-antico-gregori",
        name: "Antico Gregori",
        denom: "Vernaccia di Oristano DOC Riserva",
        type: "meditazione",
        price: 73.1,
        price_estimated: true,
        format: "0.375L",
        image: "https://vinicontini.com/wp-content/uploads/2023/06/AnticoGregori_Riserva_1991_Contini-1.png",
      },
    ],
  },
  {
    id: "monserrato",
    name: "Cantine Pauli's — Monserrato 1924",
    town: "Monserrato (Cagliari)",
    region: "Sardegna",
    founded: 1924,
    story_it:
      "Fondata il 6 luglio 1924 da 79 viticoltori, la Cantina Sociale di Monserrato è la più antica cantina sociale della Sardegna, oggi attiva con il marchio Cantine Pauli's. I vigneti dei soci si estendono per circa 300 ettari nel sud dell'isola, coltivati con i vitigni storici sardi: Monica, Nuragus, Vermentino, Cannonau, Nasco e Moscato. Nel 2024 la cooperativa ha celebrato il centenario.",
    story_en:
      "Founded on 6 July 1924 by 79 winegrowers, the Cantina Sociale di Monserrato is Sardinia's oldest cooperative winery, today trading as Cantine Pauli's. Its members' vineyards cover around 300 hectares in the south of the island, planted with the historic Sardinian varieties Monica, Nuragus, Vermentino, Cannonau, Nasco and Moscato. In 2024 the cooperative celebrated its centenary.",
    website: "https://cantinepaulis.it",
    image:
      "https://cantinepaulis.it/wp-content/uploads/cantine-paulis-monserrato-dal-1924-scelte-di-vite.jpg",
    wines: [
      {
        id: "paulis-chea",
        name: "Chea",
        denom: "Monica di Sardegna DOC",
        type: "rosso",
        price: 11.0,
        price_estimated: true,
        format: "0.75L",
        image: "https://cantinepaulis.it/wp-content/uploads/chea-monica-di-sardegna-doc-cantine-paulis-monserrato.png",
      },
      {
        id: "paulis-movida",
        name: "Movida",
        denom: "Nuragus di Cagliari DOC",
        type: "bianco",
        price: 11.0,
        price_estimated: true,
        format: "0.75L",
        image: "https://cantinepaulis.it/wp-content/uploads/movida-nuragus-di-cagliari-doc-cantine-paulis-monserrato.png",
      },
      {
        id: "paulis-evento",
        name: "Evento",
        denom: "Vermentino di Sardegna DOC",
        type: "bianco",
        price: 11.0,
        price_estimated: true,
        format: "0.75L",
        image: "https://cantinepaulis.it/wp-content/uploads/evento-vermentino-di-sardegna-doc-cantine-paulis-monserrato.png",
      },
    ],
  },
  {
    id: "guerrieri-rizzardi",
    name: "Guerrieri Rizzardi",
    town: "Bardolino (Verona)",
    region: "Veneto",
    founded: 1678,
    story_it:
      "I Rizzardi coltivano vigne in Valpolicella dal 1649 e imbottigliano i loro vini dal 1678, mentre i conti Guerrieri sviluppavano vino e olio nell'entroterra di Bardolino fin dal Seicento. Nel 1913 il matrimonio tra le due casate diede vita al nome Guerrieri Rizzardi. Oggi la terza generazione guida 100 ettari di vigneti di famiglia tra Bardolino, Valpolicella (tenuta Pojega a Negrar) e Soave, dove la Corvina firma Bardolino, Ripasso e Amarone.",
    story_en:
      "The Rizzardi family has farmed vineyards in Valpolicella since 1649 and bottled its wines since 1678, while the Counts Guerrieri built up wine and olive estates around Bardolino from the 1600s. The 1913 marriage of the two houses created the Guerrieri Rizzardi name. Today the third generation runs 100 hectares of family vineyards across Bardolino, Valpolicella (the Pojega estate in Negrar) and Soave, where Corvina shapes their Bardolino, Ripasso and Amarone.",
    website: "https://www.guerrieri-rizzardi.it",
    image: "https://www.guerrieri-rizzardi.it/wp-content/uploads/2020/04/Storia-Guerrieri-Rizzardi-header.jpg",
    wines: [
      {
        id: "gr-3cru",
        name: "3CRU 2021",
        denom: "Amarone della Valpolicella Classico DOCG",
        type: "rosso",
        price: 36.0,
        format: "0.75L",
        image: "https://www.guerrieri-rizzardi.it/wp-content/uploads/2021/09/Bottiglie-3CRU-Amarone-Della-Valpolicella-DOCG-Classico-Guerrieri-Rizzardi_store-1.jpg",
      },
      {
        id: "gr-pojega",
        name: "Pojega 2024",
        denom: "Valpolicella Ripasso Classico Superiore DOC",
        type: "rosso",
        price: 17.0,
        format: "0.75L",
        image: "https://www.guerrieri-rizzardi.it/wp-content/uploads/2020/11/Bottiglie-pojega-valpolicella-ripasso-classico-superiore-doc_store.jpg",
      },
      {
        id: "gr-cuveexx",
        name: "Cuvée XX 2025",
        denom: "Soave Classico DOC",
        type: "bianco",
        price: 9.0,
        format: "0.75L",
        image: "https://www.guerrieri-rizzardi.it/wp-content/uploads/2020/08/Bottiglie-Soave-Classico-Doc-CuveeXX-vino-bianco-Guerrieri-rizzardi.jpg",
      },
      {
        id: "gr-keya",
        name: "Keya 2025",
        denom: "Chiaretto di Bardolino Classico DOC",
        type: "rosato",
        price: 10.0,
        format: "0.75L",
        image: "https://www.guerrieri-rizzardi.it/wp-content/uploads/2021/05/Bottiglie-Keya-Chiaretto-vino-rosato-Guerrieri-Rizzardi_store.jpg",
      },
    ],
  },
  {
    id: "tasca-dalmerita",
    name: "Tasca d'Almerita",
    town: "Sclafani Bagni (Palermo)",
    region: "Sicilia",
    founded: 1830,
    story_it:
      "Nel 1830 i fratelli Tasca acquistarono la Tenuta Regaleali, un'oasi verde di 550 ettari nella contea di Sclafani, nel cuore della Sicilia. Da quasi due secoli e otto generazioni la famiglia Tasca d'Almerita valorizza i vitigni autoctoni dell'isola — su tutti il Nero d'Avola della storica vigna San Lucio, da cui nasce il Rosso del Conte. A Regaleali si sono aggiunte le tenute Capofaro a Salina, Whitaker a Mozia, Sallier de La Tour a Monreale e Tascante sull'Etna.",
    story_en:
      "In 1830 the Tasca brothers purchased Tenuta Regaleali, a 550-hectare green oasis in the county of Sclafani in the heart of Sicily. For nearly two centuries and eight generations the Tasca d'Almerita family has championed the island's native grapes — above all the Nero d'Avola of the historic San Lucio vineyard, the cradle of Rosso del Conte. To Regaleali they added the Capofaro estate on Salina, Whitaker on Mozia, Sallier de La Tour in Monreale and Tascante on Etna.",
    website: "https://tascadalmerita.it",
    image: "https://cdn.tascadalmerita.it/tasca/Tenuta-regaleali-casa_img_SocialCard.jpg",
    wines: [
      {
        id: "tasca-rosso-conte",
        name: "Rosso del Conte 2019",
        denom: "Contea di Sclafani Rosso DOC",
        type: "rosso",
        price: 55.0,
        format: "0.75L",
        image: "https://cdn.shopify.com/s/files/1/0620/5145/1073/files/RDC_2019_shop.webp",
      },
      {
        id: "tasca-nozze-oro",
        name: "Nozze d'Oro 2024",
        denom: "Sicilia Bianco DOC",
        type: "bianco",
        price: 30.0,
        format: "0.75L",
        image: "https://cdn.shopify.com/s/files/1/0620/5145/1073/files/Tenuta_regaleali_Nozzed_oro_shop_2024.webp",
      },
      {
        id: "tasca-ghiaia-nera",
        name: "Ghiaia Nera 2024",
        denom: "Etna Rosso DOC",
        type: "rosso",
        price: 24.5,
        format: "0.75L",
        image: "https://cdn.shopify.com/s/files/1/0620/5145/1073/files/Tenuta-Tascante-Ghiaia-Nera-2024-shop.webp",
      },
      {
        id: "tasca-lamuri",
        name: "Lamuri 2022",
        denom: "Sicilia Rosso DOC",
        type: "rosso",
        price: 14.5,
        format: "0.75L",
        image: "https://cdn.shopify.com/s/files/1/0620/5145/1073/files/tenuta-regaleali-lamuri-2022-shop_1.webp",
      },
    ],
  },
  {
    id: "ricasoli",
    name: "Ricasoli 1141",
    town: "Gaiole in Chianti (Siena)",
    region: "Toscana",
    founded: 1141,
    story_it:
      "La famiglia Ricasoli è legata al Castello di Brolio, a Gaiole in Chianti, dal 1141: quasi nove secoli di storia che ne fanno la più antica azienda vinicola d'Italia. Nel 1872 il barone Bettino Ricasoli ideò la formula del Chianti, oggi Chianti Classico, fondata sul Sangiovese. Dal 1993 il barone Francesco Ricasoli guida la tenuta di 1.200 ettari, con circa 240 ettari di vigneto.",
    story_en:
      "The Ricasoli family has been tied to Brolio Castle in Gaiole in Chianti since 1141 — nearly nine centuries of history that make it Italy's oldest winery. In 1872 Baron Bettino Ricasoli devised the formula for Chianti, today's Chianti Classico, built on Sangiovese. Since 1993 Baron Francesco Ricasoli has led the 1,200-hectare estate, with some 240 hectares of vineyards.",
    website: "https://www.ricasoli.com",
    image: "https://www.ricasoli.com/wp-content/uploads/2025/06/Ricasoli_Vigneto.jpg",
    wines: [
      {
        id: "ricasoli-brolio",
        name: "Brolio 2024",
        denom: "Chianti Classico DOCG",
        type: "rosso",
        price: 16.5,
        format: "0.75L",
        image: "https://eshop.ricasoli.com/media/img/product/671/Brolio_2019NV_ombra_full.png",
      },
      {
        id: "ricasoli-brolio-riserva",
        name: "Brolio Riserva 2023",
        denom: "Chianti Classico Riserva DOCG",
        type: "rosso",
        price: 24.9,
        format: "0.75L",
        image: "https://eshop.ricasoli.com/media/img/product/679/9562e-Brolio_Ris_2018NV_ombra_full.png",
      },
      {
        id: "ricasoli-castello",
        name: "Castello di Brolio Gran Selezione 2022",
        denom: "Chianti Classico Gran Selezione DOCG",
        type: "rosso",
        price: 49.0,
        format: "0.75L",
        image: "https://eshop.ricasoli.com/media/img/product/599/Castello_Gaiole_NV_full.png",
      },
      {
        id: "ricasoli-colledila",
        name: "Colledilà Gran Selezione 2022",
        denom: "Chianti Classico Gran Selezione DOCG",
        type: "rosso",
        price: 64.0,
        format: "0.75L",
        image: "https://eshop.ricasoli.com/media/img/product/601/Colledil%C3%A0_Gaiole_NV_full.png",
      },
    ],
  },
];
